spring:
  application:
    name: maven.project
  lifecycle:
    timeout-per-shutdown-phase: 1m  #  처리 중인 요청이 완료될 때까지 기다려주는 타임아웃 설정

server:
  address: localhost
  port: 8081
  shutdown: graceful  # 안전 종료 설정

# 모든 액추에이터 엔드포인트를 HTTP 로 공개
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 커스텀 애플리케이션 프로퍼티
app:
  sbip:
    ct:
      name: CourseTracker
      ip: 127.0.0.1
      port: 9090
      security:
        enabled: true
        token: asdf998hhyqthgthgtYYtggghg9908jjh7ttr
        roles: USER,ADMIN
