spring:
  application:
    name: maven.project
  lifecycle:
    timeout-per-shutdown-phase: 1m  #  처리 중인 요청이 완료될 때까지 기다려주는 타임아웃 설정
  datasource:
    url: jdbc:h2:mem:sbipdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:sql/schema/sbip-schema.sql
#      data-locations: classpath:sql/data/sbip-data.sql
  jpa:
    hibernate:
      # ddl 관리 설정 (none, validate, update, create, create-drop)
      # none: ddl 자동 생성 및 관리 기능을 비활성화 한다. 임베디드가 아닌 실제 데이터베이스에서 기본 값
      # validate: 실제 데이터베이스에 있는 스키마와 자동 생성되는 ddl 을 비교 검증해서 차이가 있으면 데이터베이스에 반영하지 않고, 스프링 부트 애플리케이션 시작 시 에러 발생
      # update: 실제 데이터베이스에 있는 스키마와 자동 생성되는 ddl 을 비교 검증해서 차이가 있으면 자동으로 생성되는 ddl 기준으로 변경 사항을 데이터베이스에 반영
      # create: 기존에 존재하던 스키마와 데이터를 삭제하고 스키마를 새로 생성
      # create-drop: 기존에 존재하던 스키마와 데이터를 삭제하고 스키마를 새로 생성하고 애플리케이션 종료 시 스키마와 데이터를 삭제한다. 임베디드 데이터베이스 사용 시 기본 값
      ddl-auto: none
      # 하이버네이트 외의 다른 JPA 구현체에서도 동작하게 하기 위한 설정
      generate-ddl: false

server:
  address: localhost
  port: 8081
  shutdown: graceful  # 안전 종료 설정

# 모든 액추에이터 엔드포인트를 HTTP 로 공개
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 커스텀 애플리케이션 프로퍼티
app:
  sbip:
    ct:
      name: CourseTracker
      ip: 127.0.0.1
      port: 9090
      security:
        enabled: true
        token: asdf998hhyqthgthgtYYtggghg9908jjh7ttr
        roles: USER,ADMIN

logging:
  level:
#    root: DEBUG
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE
